#!/bin/bash
# use some variables, some command substituion and some string formatting to make
# a small summar of some system inforation.
# print the result to the screen and write some information to a file.

# command substitution and pipe
freespace=$(df -h / | grep -E "\/$" | awk '{print $4}')

# style 
greentext="\033[32m"
bold="\033[1m"
normal="\033[0m"
logdate=$(date +"%Y%m%d")

# string concatenation
logfile="$logdate"_report.log

# escape style 
# built-in variable $HOSTNAME
echo -e $bold"Quick system report for "$greentext"$HOSTNAME"$normal
printf "\tSystem type:\t%s\n" $MACHTYPE
printf "\tBash Version:\t%s\n" $BASH_VERSION
printf "\tFree Space:\t%s\n" $freespace
printf "\tFiles in dir:\t%s\n" $(ls | wc -l)
printf "\tGenerated on:\t%s\n" $(date +"%m/%d/%y") # US date format
echo -e $greentext"A summary of this info has been saved to $logfile"$normal

# here document and redirect cat output to a file
cat <<- EOF > $logfile 
	This report was automatically generated by my Bash script.
	It contains a brief summary of some system information.
EOF

# append to the file
printf "SYS:\t%s\n" $MACHTYPE >> $logfile
printf "BASH:\t%s\n" $BASH_VERSION >> $logfile

